# Use official Node.js LTS image
FROM node:lts

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY frontend/package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of the frontend application code
COPY frontend/ .

# Expose the port the app runs on
EXPOSE 8080

# Command to run the development server
CMD ["npm", "run", "serve"]
