version: '3.8'

services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  vue-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: vue-app
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "8080:8080"
    environment:
      - VITE_OLLAMA_API_URL=http://ollama:11434
      - NODE_ENV=development
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data:
  node_modules:
