# Use official Node.js LTS image
FROM node:lts

# Set working directory
WORKDIR /app

# Install Vue CLI globally
RUN npm install -g @vue/cli @vue/cli-service

# Copy package files
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY frontend/ .


# Expose the development server port
EXPOSE 8080

# Start the development server
CMD ["npm", "run", "serve"]
